### PR TITLE
Add checkDownload to customRouteForDownload

### PR DESCRIPTION
**Pull request by vgallur-sword**
Add checkDownload hook to allow the client to check and abort the download, like in cases where it belongs to a deleted node

### CODE REVIEW

**Comment by jgovaerts** [comment]
The code changes seems to be OK, but could you also extend the test suite with a test to check the added functionality?

**Comment by vgallur-sword** [comment]
Hi @jgovaerts, I added one test server section to be able to configure sri4node with the hook to be tested. Please let me know if that's fine or you are thinking in another way to do it.

**Comment by jgovaerts** [comment]
A new test server section to test this seems a good approach to test this. But I would make the checkParentDeleted function not always throw an error but only in a certain case which can be triggered from within the test case (like a specific query parameter 'simulateParentDeleted=true'). This way you can also add a positive test case to the new server section besides the negative one, to make sure the download is working in case checkDownload did not throw.

**Comment by vgallur-sword** [comment]
I added a couple more tests

**Pull request merged**
